#!/bin/sh
git clone --depth=1       git@github.com:robbyrussell/oh-my-zsh.git common/.oh-my-zsh
git clone --depth=1 -b my git@github.com:myrgy/fork-spacemacs.git common/.emacs.d
git clone --depth=1       git@github.com:myrgy/dotspacemacs.d.git common/.spacemacs.d
